# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
name: Vladimír Mezera blog
description: My blog
url: http://vladimirmezera.github.com

title:            Blog
tagline:          'theme'
description:      ''
url:              http://github.com/vladimirmezera
baseurl:          /

author:
  name:           'Vladimir Mezera'
  url:            https://twitter.com/vladimirmezera

paginate:         5

# Custom vars
version:          1.0.0.

github:
  repo:           https://github.com/vladimirmezera
